name: troona
description: An open source Music Player App build with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons for IOS
  cupertino_icons: ^1.0.6

  # Neumorphic ui kit for Flutter.
  flutter_neumorphic_plus: ^3.3.0

  # Easy translations, React and persist to locale changes.
  easy_localization: ^3.0.3

  # Adapting screen and font size.Guaranteed to look good on different models.
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    - assets/locales/
    - assets/google_fonts/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Nunito-Black.ttf
          weight: 900
