name: troona
description: An open source Music Player App build with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons for IOS
  cupertino_icons: ^1.0.6

  # Neumorphic ui kit for Flutter.
  flutter_neumorphic_plus: ^3.3.0

  # Easy translations, React and persist to locale changes.
  easy_localization: ^3.0.3

  # Adapting screen and font size.Guaranteed to look good on different models.
  flutter_screenutil: ^5.9.0

  # Implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  # Lightweight and blazing fast key-value database written in pure Dart.
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Officially endorsed state management library with O(1) access time from
  # anywhere in the widget tree
  path: ^1.8.3
  provider: ^6.0.5

  # Supplies the app with the directory location for storing files
  path_provider: ^2.1.1

  # Simplify the creation of a miniplayer.
  miniplayer: ^1.0.1

  # Show simple music visualizer animation
  mini_music_visualizer: ^1.0.2

  # Service Locator
  get_it: ^7.6.4

  # pre-canned animations for commonly-desired effects
  animations: ^2.0.8

  # Powerful package to create beautiful custom animations in no time.
  simple_animations: ^5.0.2

  # A feature-rich audio player
  just_audio: ^0.9.35

  # To play audio in the background while the screen is off.
  audio_service: ^0.18.12
  audio_session: ^0.1.16

  # A Flutter implementation of React hooks
  flutter_hooks: ^0.20.3

  # An SVG rendering
  flutter_svg: ^2.0.8

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.4.0

  # query audios/tracks 🎶 from device storage.
  on_audio_query: ^2.9.0

  # Create a room to storage audio sections
  on_audio_room: ^2.2.1+1

  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    - assets/icons/
    - assets/locales/
    - assets/google_fonts/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Nunito-Black.ttf
          weight: 900